package parse

import (
	"strings"
	"testing"
)

const sample = `# Generated by iptables-save v1.8.7 on Tue Jul 21 12:00:00 2026
*filter
:INPUT ACCEPT [1234:56789]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [111:222]
[123:4567] -A INPUT -p icmp -m icmp --icmp-type 8 -j ACCEPT
[89:1011] -A INPUT -j DROP -m comment --comment "iptables-exporter default_last_dropped"
[5:600] -A INPUT -p tcp -m tcp --dport 22 -m comment --comment "unrelated comment" -j ACCEPT
COMMIT
*nat
:PREROUTING ACCEPT [0:0]
[7:800] -A PREROUTING -p tcp -m comment --comment "iptables-exporter nat_test" -j ACCEPT
COMMIT
`

func TestParse(t *testing.T) {
	rules := Parse(strings.NewReader(sample), "ipv4", "iptables-exporter ")
	if len(rules) != 2 {
		t.Fatalf("ожидалось 2 правила, получено %d: %+v", len(rules), rules)
	}

	r0 := rules[0]
	if r0.Table != "filter" || r0.Chain != "INPUT" || r0.Label != "default_last_dropped" ||
		r0.Packets != 89 || r0.Bytes != 1011 {
		t.Errorf("неверно распознано правило filter/INPUT: %+v", r0)
	}

	r1 := rules[1]
	if r1.Table != "nat" || r1.Chain != "PREROUTING" || r1.Label != "nat_test" ||
		r1.Packets != 7 || r1.Bytes != 800 {
		t.Errorf("неверно распознано правило nat/PREROUTING: %+v", r1)
	}
}

func TestParseIgnoresUnlabeled(t *testing.T) {
	rules := Parse(strings.NewReader(sample), "ipv4", "iptables-exporter ")
	for _, r := range rules {
		if r.Label == "unrelated comment" {
			t.Errorf("правило без нашего префикса не должно попадать в результат: %+v", r)
		}
	}
}
